/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bakerypossystem.View;

import bakerypossystem.Model.BillsnPaymentCalculation;
import bakerypossystem.Model.DatabaseConnector;
import bakerypossystem.Model.ItemCartDatabase;
import bakerypossystem.Model.PDFGenerator;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author thenu
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
         try {

             FlatDarkLaf.setup();
     
        } catch (Exception e) {
             printStackTrace(e);
        }
        initComponents();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
       
        btnPay.setEnabled(false);
        paidCashtxt.setEnabled(false);
       

    }


  public void addtable(int id, String Name, int Qty, Double Price) {
    DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
    DecimalFormat df = new DecimalFormat("00.00");
    double totPrice = Price * Double.valueOf(Qty);
    String TotalPrice = df.format(totPrice);

    // Iterate through the rows to find and remove rows with matching names
    for (int row = 0; row < jTable1.getRowCount(); row++) {
        String tableName = (String) jTable1.getValueAt(row, 1);
        if (Name.equals(tableName)) {
            dt.removeRow(jTable1.convertRowIndexToModel(row));
            break; // Assuming each item name is unique
        }
    }

    Vector<Object> v = new Vector<>();
    v.add(id);
    v.add(Name);
    v.add(Qty);
    v.add(TotalPrice); // total price

    dt.addRow(v);
}
    public void cal(){
    //cal total table values
   
   int numOfRow = jTable1.getRowCount() ;
   double tot = 0.0 ;
   
       for (int i = 0; i < numOfRow; i++) {
           
           double value = Double.valueOf(jTable1.getValueAt(i, 3).toString());
          
           tot += value ;
           
       }
       
       DecimalFormat df = new DecimalFormat("00.00") ;
       total.setText(df.format(tot));
    
   
   
   } 

     /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        DetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        paidCashtxt = new javax.swing.JTextField();
        lblbalance = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btndrinks1 = new javax.swing.JButton();
        dq1 = new javax.swing.JLabel();
        btndrinks2 = new javax.swing.JButton();
        dq2 = new javax.swing.JLabel();
        btndrinks3 = new javax.swing.JButton();
        btndrinks4 = new javax.swing.JButton();
        dq3 = new javax.swing.JLabel();
        dq4 = new javax.swing.JLabel();
        dq5 = new javax.swing.JLabel();
        btndrinks5 = new javax.swing.JButton();
        btndrinks6 = new javax.swing.JButton();
        dq6 = new javax.swing.JLabel();
        btndrinks7 = new javax.swing.JButton();
        btndrinks8 = new javax.swing.JButton();
        dq7 = new javax.swing.JLabel();
        dq8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnfood1 = new javax.swing.JButton();
        q1 = new javax.swing.JLabel();
        btnfood2 = new javax.swing.JButton();
        q2 = new javax.swing.JLabel();
        btnfood3 = new javax.swing.JButton();
        q3 = new javax.swing.JLabel();
        btnfood4 = new javax.swing.JButton();
        q4 = new javax.swing.JLabel();
        btnfood5 = new javax.swing.JButton();
        q5 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        btnfood6 = new javax.swing.JButton();
        q7 = new javax.swing.JLabel();
        btnfood7 = new javax.swing.JButton();
        btnfood8 = new javax.swing.JButton();
        qq9 = new javax.swing.JLabel();
        qq7 = new javax.swing.JLabel();
        btnfood9 = new javax.swing.JButton();
        q10 = new javax.swing.JLabel();
        btnfood10 = new javax.swing.JButton();
        btnfood11 = new javax.swing.JButton();
        q11 = new javax.swing.JLabel();
        q12 = new javax.swing.JLabel();
        btnfood12 = new javax.swing.JButton();
        btnfood13 = new javax.swing.JButton();
        btnfood14 = new javax.swing.JButton();
        btnfood15 = new javax.swing.JButton();
        fq13 = new javax.swing.JLabel();
        fq14 = new javax.swing.JLabel();
        fq15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 120));

        DetailsPanel.setBackground(new java.awt.Color(190, 185, 181));
        DetailsPanel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cash :");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Balance :");

        btnPay.setBackground(new java.awt.Color(0, 153, 51));
        btnPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnPurchase.setBackground(new java.awt.Color(0, 153, 51));
        btnPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPurchase.setForeground(new java.awt.Color(255, 255, 255));
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total.setText("0");

        btnClear.setBackground(new java.awt.Color(0, 153, 51));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(0, 153, 51));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        paidCashtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidCashtxtKeyTyped(evt);
            }
        });

        lblbalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbalance.setForeground(new java.awt.Color(0, 0, 0));
        lblbalance.setText("0");

        jScrollPane2.setBackground(new java.awt.Color(190, 185, 181));

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Qty", "Price"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 102, 0));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paidCashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addComponent(btnPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(total))
                        .addGap(8, 8, 8)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paidCashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPurchase)
                            .addComponent(btnPay))
                        .addGap(159, 159, 159))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addGap(266, 266, 266))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(190, 185, 181));

        btndrinks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshakepink.png"))); // NOI18N
        btndrinks1.setBorder(null);
        btndrinks1.setPreferredSize(new java.awt.Dimension(160, 196));
        btndrinks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks1ActionPerformed(evt);
            }
        });

        dq1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq1.setForeground(new java.awt.Color(0, 0, 0));
        dq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq1.setText("0");
        dq1.setToolTipText("");

        btndrinks2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshake (1).png"))); // NOI18N
        btndrinks2.setBorder(null);
        btndrinks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks2ActionPerformed(evt);
            }
        });

        dq2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq2.setForeground(new java.awt.Color(0, 0, 0));
        dq2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq2.setText("0");
        dq2.setToolTipText("");

        btndrinks3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshake (3).png"))); // NOI18N
        btndrinks3.setBorder(null);
        btndrinks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks3ActionPerformed(evt);
            }
        });

        btndrinks4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/banana.png"))); // NOI18N
        btndrinks4.setBorder(null);
        btndrinks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks4ActionPerformed(evt);
            }
        });

        dq3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq3.setForeground(new java.awt.Color(0, 0, 0));
        dq3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq3.setText("0");
        dq3.setToolTipText("");

        dq4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq4.setForeground(new java.awt.Color(0, 0, 0));
        dq4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq4.setText("0");
        dq4.setToolTipText("");

        dq5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq5.setForeground(new java.awt.Color(0, 0, 0));
        dq5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq5.setText("0");
        dq5.setToolTipText("");

        btndrinks5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshake (5).png"))); // NOI18N
        btndrinks5.setBorder(null);
        btndrinks5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks5ActionPerformed(evt);
            }
        });

        btndrinks6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/smoothie.png"))); // NOI18N
        btndrinks6.setBorder(null);
        btndrinks6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks6ActionPerformed(evt);
            }
        });

        dq6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq6.setForeground(new java.awt.Color(0, 0, 0));
        dq6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq6.setText("0");
        dq6.setToolTipText("");

        btndrinks7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshake (2).png"))); // NOI18N
        btndrinks7.setBorder(null);
        btndrinks7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks7ActionPerformed(evt);
            }
        });

        btndrinks8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/milkshake.png"))); // NOI18N
        btndrinks8.setBorder(null);
        btndrinks8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinks8ActionPerformed(evt);
            }
        });

        dq7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq7.setForeground(new java.awt.Color(0, 0, 0));
        dq7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq7.setText("0");
        dq7.setToolTipText("");

        dq8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dq8.setForeground(new java.awt.Color(0, 0, 0));
        dq8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dq8.setText("0");
        dq8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dq1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btndrinks6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btndrinks3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dq2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dq8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndrinks8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndrinks8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dq8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuPanel.setBackground(new java.awt.Color(190, 185, 181));
        MenuPanel.setForeground(new java.awt.Color(190, 185, 181));

        jScrollPane1.setBackground(new java.awt.Color(190, 185, 181));
        jScrollPane1.setForeground(new java.awt.Color(190, 185, 181));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(190, 185, 181));

        btnfood1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-1.png"))); // NOI18N
        btnfood1.setBorder(null);
        btnfood1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood1ActionPerformed(evt);
            }
        });

        q1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q1.setForeground(new java.awt.Color(0, 0, 0));
        q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q1.setText("0");
        q1.setToolTipText("");

        btnfood2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-10.png"))); // NOI18N
        btnfood2.setBorder(null);
        btnfood2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood2ActionPerformed(evt);
            }
        });

        q2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q2.setForeground(new java.awt.Color(0, 0, 0));
        q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q2.setText("0");
        q2.setToolTipText("");

        btnfood3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-11.png"))); // NOI18N
        btnfood3.setBorder(null);
        btnfood3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood3ActionPerformed(evt);
            }
        });

        q3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q3.setForeground(new java.awt.Color(0, 0, 0));
        q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q3.setText("0");
        q3.setToolTipText("");

        btnfood4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-13.png"))); // NOI18N
        btnfood4.setBorder(null);
        btnfood4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood4ActionPerformed(evt);
            }
        });

        q4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q4.setForeground(new java.awt.Color(0, 0, 0));
        q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q4.setText("0");
        q4.setToolTipText("");

        btnfood5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-12.png"))); // NOI18N
        btnfood5.setBorder(null);
        btnfood5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood5ActionPerformed(evt);
            }
        });

        q5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q5.setForeground(new java.awt.Color(0, 0, 0));
        q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q5.setText("0");
        q5.setToolTipText("");

        q6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q6.setForeground(new java.awt.Color(0, 0, 0));
        q6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q6.setText("0");
        q6.setToolTipText("");

        btnfood6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-14.png"))); // NOI18N
        btnfood6.setBorder(null);
        btnfood6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood6ActionPerformed(evt);
            }
        });

        q7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q7.setForeground(new java.awt.Color(0, 0, 0));
        q7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q7.setText("0");
        q7.setToolTipText("");

        btnfood7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-16.png"))); // NOI18N
        btnfood7.setBorder(null);
        btnfood7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood7ActionPerformed(evt);
            }
        });

        btnfood8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-15.png"))); // NOI18N
        btnfood8.setBorder(null);
        btnfood8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood8ActionPerformed(evt);
            }
        });

        qq9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qq9.setForeground(new java.awt.Color(0, 0, 0));
        qq9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qq9.setText("0");
        qq9.setToolTipText("");

        qq7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qq7.setForeground(new java.awt.Color(0, 0, 0));
        qq7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qq7.setText("0");
        qq7.setToolTipText("");

        btnfood9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-2.png"))); // NOI18N
        btnfood9.setBorder(null);
        btnfood9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood9ActionPerformed(evt);
            }
        });

        q10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q10.setForeground(new java.awt.Color(0, 0, 0));
        q10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q10.setText("0");
        q10.setToolTipText("");

        btnfood10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-18.png"))); // NOI18N
        btnfood10.setBorder(null);
        btnfood10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood10ActionPerformed(evt);
            }
        });

        btnfood11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-6.png"))); // NOI18N
        btnfood11.setBorder(null);
        btnfood11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood11ActionPerformed(evt);
            }
        });

        q11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q11.setForeground(new java.awt.Color(0, 0, 0));
        q11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q11.setText("0");
        q11.setToolTipText("");

        q12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        q12.setForeground(new java.awt.Color(0, 0, 0));
        q12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q12.setText("0");
        q12.setToolTipText("");

        btnfood12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-30.png"))); // NOI18N
        btnfood12.setBorder(null);
        btnfood12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood12ActionPerformed(evt);
            }
        });

        btnfood13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-8.png"))); // NOI18N
        btnfood13.setBorder(null);
        btnfood13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood13ActionPerformed(evt);
            }
        });

        btnfood14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-33.png"))); // NOI18N
        btnfood14.setBorder(null);
        btnfood14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood14ActionPerformed(evt);
            }
        });

        btnfood15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Untitled-36.png"))); // NOI18N
        btnfood15.setBorder(null);
        btnfood15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfood15ActionPerformed(evt);
            }
        });

        fq13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fq13.setForeground(new java.awt.Color(0, 0, 0));
        fq13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fq13.setText("0");
        fq13.setToolTipText("");

        fq14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fq14.setForeground(new java.awt.Color(0, 0, 0));
        fq14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fq14.setText("0");
        fq14.setToolTipText("");

        fq15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fq15.setForeground(new java.awt.Color(0, 0, 0));
        fq15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fq15.setText("0");
        fq15.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnfood1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qq7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fq13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnfood2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fq14, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnfood3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qq9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfood12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfood15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fq15, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 461, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qq7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qq9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fq13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood14, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fq14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfood15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fq15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 440, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfood10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood10ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 11";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q11.getText());
                ++i;
                
                q11.setText(String.valueOf(i));
                
                addtable(11, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood10ActionPerformed

    private void btnfood1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood1ActionPerformed
        // TODO add your handling code here:
             String query = "SELECT Name,Price FROM bakeryitem where ItemID = 1";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q1.getText());
                ++i;
                
                q1.setText(String.valueOf(i));
                
                addtable(1, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
        
    }//GEN-LAST:event_btnfood1ActionPerformed

    private void btnfood2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood2ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 2";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q2.getText());
                ++i;
                
                q2.setText(String.valueOf(i));
                
                addtable(2, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood2ActionPerformed

    private void btnfood3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood3ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 3";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q3.getText());
                ++i;
                
                q3.setText(String.valueOf(i));
                
                addtable(3, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood3ActionPerformed
    
    private void btnfood4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood4ActionPerformed
        // TODO add your handling code here:
             String query = "SELECT Name,Price FROM bakeryitem where ItemID = 4";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q4.getText());
                ++i;
                
                q4.setText(String.valueOf(i));
                
                addtable(4, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood4ActionPerformed

    private void btnfood5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood5ActionPerformed
        // TODO add your handling code here:
             String query = "SELECT Name,Price FROM bakeryitem where ItemID = 5";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q5.getText());
                ++i;
                
                q5.setText(String.valueOf(i));
                
                addtable(5, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood5ActionPerformed

    private void btnfood6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood6ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 6";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q6.getText());
                ++i;
                
                q6.setText(String.valueOf(i));
                
                addtable(6, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood6ActionPerformed

    private void btnfood8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood8ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 7";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(qq7.getText());
                ++i;
                
                qq7.setText(String.valueOf(i));
                
                addtable(7, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood8ActionPerformed

    private void btnfood7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood7ActionPerformed
        // TODO add your handling code here:
                    String query = "SELECT Name,Price FROM bakeryitem where ItemID = 8";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q7.getText());
                ++i;
                
                q7.setText(String.valueOf(i));
                
                addtable(8, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood7ActionPerformed

    private void btnfood9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood9ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 9";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(qq9.getText());
                ++i;
                
                qq9.setText(String.valueOf(i));
                
                addtable(9, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood9ActionPerformed

    private void btnfood11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood11ActionPerformed
        // TODO add your handling code here:
                String query = "SELECT Name,Price FROM bakeryitem where ItemID = 10";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q10.getText());
                ++i;
                
                q10.setText(String.valueOf(i));
                
                addtable(10, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood11ActionPerformed

    private void btnfood12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood12ActionPerformed
        // TODO add your handling code here:
     String query = "SELECT Name,Price FROM bakeryitem where ItemID = 12";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(q12.getText());
                ++i;
                
                q12.setText(String.valueOf(i));
                
                addtable(12, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood12ActionPerformed
    int orderNumber = 0;
    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        
            int msgcheck = 0;
             // 4-digit random order number
            orderNumber = (int) (Math.random() * 9000) + 10000;
        ItemCartDatabase itemCartDatabase= new ItemCartDatabase();
 
           int rowCount = jTable1.getRowCount();

              
                for (int i = 0; i < rowCount; i++) {
                    int id = (int) jTable1.getValueAt(i, 0);
                    String item = (String) jTable1.getValueAt(i, 1);
                    int qty = (int) jTable1.getValueAt(i, 2);
                    double price = Double.parseDouble((String) jTable1.getValueAt(i, 3));
                    msgcheck = i;
                    // insert database method
                  itemCartDatabase.addItemToCart(id, item, qty, price,orderNumber);
                }
                    // Check if at least one row was affected
                if (msgcheck + 1 == rowCount) {
                    btnPurchase.setEnabled(false);
                    btnClear.setEnabled(false);
                    btnRemove.setEnabled(false);
                    btnPay.setEnabled(true);
                    paidCashtxt.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Order placed successfully. Your order number is: " + orderNumber);
                } else {
              
                    JOptionPane.showMessageDialog(null, "Failed to place the order.");
                }
   
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        btnPurchase.setEnabled(true);
        btnRemove.setEnabled(true);
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
                         
        q1.setText("0"); q2.setText("0");q3.setText("0");q4.setText("0"); q5.setText("0");q6.setText("0");
        q7.setText("0");qq9.setText("0"); qq7.setText("0");q10.setText("0");q11.setText("0");q12.setText("0");
        fq13.setText("0");fq14.setText("0");fq15.setText("0");
        //drinks 
        dq1.setText("0");dq3.setText("0");dq2.setText("0");dq4.setText("0");dq5.setText("0");dq6.setText("0");
        dq7.setText("0");dq8.setText("0");
        total.setText("0");lblbalance.setText("0");paidCashtxt.setText("0");
        
                  
        cal();
       
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
         String r = null;
               try{
       int SelectedRowIndex = jTable1.getSelectedRow();
       r = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
       model.removeRow(SelectedRowIndex);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Nothing Selected");
       }
              
        switch (r) {
                   
                   case "1":                       
                   q1.setText("0");
                   break;
                   case "2":                       
                   q2.setText("0");
                   break;
                   case "3":                       
                   q3.setText("0");
                   break;
                   case "4":                       
                   q4.setText("0");
                   break;
                   case "5":                       
                   q5.setText("0");
                   break;
                   case "6":                       
                   q6.setText("0");
                   case "7":                       
                   q7.setText("0");
                   break;
                   case "8":                       
                   qq9.setText("0");
                   break;
                   case "9":                       
                   qq7.setText("0");
                   break;
                   case "10":                       
                   q10.setText("0");
                   break;
                   case "11":                       
                   q11.setText("0");
                   break;
                   case "12":                       
                   q12.setText("0");
                   break;
                    case "13":                       
                   fq13.setText("0");
                   break;
                   case "14":                       
                   fq14.setText("0");
                   break;
                   case "15":                       
                   fq15.setText("0");
                   case "21":                       
                   dq1.setText("0");
                   break;
                   case "22":                       
                   dq2.setText("0");
                   break;
                   case "23":                       
                   dq3.setText("0");
                   break;
                   case "24":                       
                   dq4.setText("0");
                   break;
                   case "25":                       
                   dq5.setText("0");
                   break;
                   case "26":                       
                   dq6.setText("0");
                   break;
                   case "27":                       
                   dq7.setText("0");
                   break;
                   case "28":                       
                   dq8.setText("0");
                   break;
                   
                   default:
                       System.out.println("Finish");
               }
    cal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        
        BillsnPaymentCalculation cal = new BillsnPaymentCalculation();        
        
        double tot = Double.parseDouble(total.getText());
        double paid = Double.parseDouble(paidCashtxt.getText());
          DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
   
         ItemCartDatabase itemCartDatabase= new ItemCartDatabase();
 
           int rowCount = jTable1.getRowCount();

              
                for (int i = 0; i < rowCount; i++) {
                    int id = (int) jTable1.getValueAt(i, 0);
                    String item = (String) jTable1.getValueAt(i, 1);
                    int qty = (int) jTable1.getValueAt(i, 2);
                    double price = Double.parseDouble((String) jTable1.getValueAt(i, 3));

                    // insert database method
                  itemCartDatabase.addToSales(id, item, qty, price,orderNumber);
                }
        
         // Calling Bill Calculate Function
       double bal = cal.balanceCal(tot, paid);
       DecimalFormat dfd = new DecimalFormat("00.00") ;
       lblbalance.setText(dfd.format(bal));
       
        
        String shopName = "Induwara Kannangara Bakery Shop";
        String shopAddress = "Gampaha,Srilanka";
        String shopContact = "Gampaha, Sri Lanka, +94774746138";
        
        // Create a list to store bill items
        List<String[]> billItems = new ArrayList<>();

        // Add your bill items to the list
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String name = tableModel.getValueAt(i, 1).toString();
            String qty = tableModel.getValueAt(i, 2).toString();
            String price = tableModel.getValueAt(i, 3).toString();
            billItems.add(new String[]{name, qty, price});
        }
        
        String subTotal = total.getText();
        String cash =paidCashtxt.getText();
        String balance = lblbalance.getText();
      
        if(paid <tot){
    
        }
        else{
         paidCashtxt.setEnabled(false);
             btnPay.setEnabled(false);
        btnClear.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Thankyou For Purchasing our Order!");
        }
        
        
    
        
        PDFGenerator.generateBillPDF(shopName, shopAddress, shopContact, billItems, subTotal, cash, balance);


        
      
    }//GEN-LAST:event_btnPayActionPerformed

    private void paidCashtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidCashtxtKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
                String text = paidCashtxt.getText();

                if (!((c >= '0' && c <= '9') || (c == '.' && !text.contains(".")) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                    evt.consume(); // Ignore input that isn't a number or a period
                }
    }//GEN-LAST:event_paidCashtxtKeyTyped

    private void btndrinks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks1ActionPerformed
        // TODO add your handling code here:
            String query = "SELECT Name,Price FROM bakeryitem where ItemID = 21";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq1.getText());
                ++i;
                
                dq1.setText(String.valueOf(i));
                
                addtable(21, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks1ActionPerformed

    private void btndrinks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks2ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 22";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq2.getText());
                ++i;
                
                dq2.setText(String.valueOf(i));
                
                addtable(22, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks2ActionPerformed

    private void btndrinks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks3ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 23";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq3.getText());
                ++i;
                
                dq3.setText(String.valueOf(i));
                
                addtable(23, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks3ActionPerformed

    private void btndrinks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks4ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 24";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq4.getText());
                ++i;
                
                dq4.setText(String.valueOf(i));
                
                addtable(24, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks4ActionPerformed

    private void btndrinks5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks5ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 25";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq6.getText());
                ++i;
                
                dq6.setText(String.valueOf(i));
                
                addtable(25, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks5ActionPerformed

    private void btndrinks6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks6ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 26";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq5.getText());
                ++i;
                
                dq5.setText(String.valueOf(i));
                
                addtable(26, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks6ActionPerformed

    private void btndrinks7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks7ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 27";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq7.getText());
                ++i;
                
                dq7.setText(String.valueOf(i));
                
                addtable(27, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks7ActionPerformed

    private void btndrinks8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinks8ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 28";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(dq8.getText());
                ++i;
                
                dq8.setText(String.valueOf(i));
                
                addtable(28, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btndrinks8ActionPerformed

    private void btnfood13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood13ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 13";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(fq13.getText());
                ++i;
                
                fq13.setText(String.valueOf(i));
                
                addtable(13, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood13ActionPerformed

    private void btnfood14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood14ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 14";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(fq14.getText());
                ++i;
                
                fq14.setText(String.valueOf(i));
                
                addtable(14, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood14ActionPerformed

    private void btnfood15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfood15ActionPerformed
        // TODO add your handling code here:
                   String query = "SELECT Name,Price FROM bakeryitem where ItemID = 15";
     DatabaseConnector dbConnector = new DatabaseConnector();
     ResultSet resultSet = dbConnector.retrieveData(query);
    
        try {
            // Assuming your JTable column names are "Item Name" and "Price"
            
            while (resultSet.next()) {
                String itemName = resultSet.getString("Name");
                double price = resultSet.getDouble("Price");
                int i = Integer.valueOf(fq15.getText());
                ++i;
                
                fq15.setText(String.valueOf(i));
                
                addtable(15, itemName, i, price);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Handling Data!");
        }
        cal();
    }//GEN-LAST:event_btnfood15ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btndrinks1;
    private javax.swing.JButton btndrinks2;
    private javax.swing.JButton btndrinks3;
    private javax.swing.JButton btndrinks4;
    private javax.swing.JButton btndrinks5;
    private javax.swing.JButton btndrinks6;
    private javax.swing.JButton btndrinks7;
    private javax.swing.JButton btndrinks8;
    private javax.swing.JButton btnfood1;
    private javax.swing.JButton btnfood10;
    private javax.swing.JButton btnfood11;
    private javax.swing.JButton btnfood12;
    private javax.swing.JButton btnfood13;
    private javax.swing.JButton btnfood14;
    private javax.swing.JButton btnfood15;
    private javax.swing.JButton btnfood2;
    private javax.swing.JButton btnfood3;
    private javax.swing.JButton btnfood4;
    private javax.swing.JButton btnfood5;
    private javax.swing.JButton btnfood6;
    private javax.swing.JButton btnfood7;
    private javax.swing.JButton btnfood8;
    private javax.swing.JButton btnfood9;
    private javax.swing.JLabel dq1;
    private javax.swing.JLabel dq2;
    private javax.swing.JLabel dq3;
    private javax.swing.JLabel dq4;
    private javax.swing.JLabel dq5;
    private javax.swing.JLabel dq6;
    private javax.swing.JLabel dq7;
    private javax.swing.JLabel dq8;
    private javax.swing.JLabel fq13;
    private javax.swing.JLabel fq14;
    private javax.swing.JLabel fq15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JTextField paidCashtxt;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q11;
    private javax.swing.JLabel q12;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel qq7;
    private javax.swing.JLabel qq9;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

    private void printStackTrace(Exception e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
