/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bakerypossystem.View;

import bakerypossystem.Model.DailyTopItemsPieChartPanel;
import bakerypossystem.Model.OrderDetails;
import bakerypossystem.Model.PendingCompleted;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.BorderLayout;





/**
 *
 * @author thenu
 */
public class DashboardPanel extends javax.swing.JPanel {

   private final OrderDetails orderDetailsManager;
    public DashboardPanel() {
         try {
             FlatDarkLaf.setup();
     
        } catch (Exception e) {
             printStackTrace(e);
        }
        initComponents();
        // Initialize the OrderDetails manager and pass the JComboBox and JTextArea
        orderDetailsTextArea.setEditable(false);
        orderDetailsManager = new OrderDetails();
        orderDetailsManager.initializeComponents(orderNumberDropdown, orderDetailsTextArea);
        DailyTopItemsPieChartPanel chart = new DailyTopItemsPieChartPanel();
        PieChartPanel.setLayout(new BorderLayout());
        PieChartPanel.add(chart, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderNumberDropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PieChartPanel = new javax.swing.JPanel();
        btnOrderClear = new javax.swing.JButton();

        orderNumberDropdown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderNumberDropdown.setForeground(new java.awt.Color(255, 255, 255));
        orderNumberDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderNumberDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderNumberDropdownMouseClicked(evt);
            }
        });
        orderNumberDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNumberDropdownActionPerformed(evt);
            }
        });

        orderDetailsTextArea.setColumns(20);
        orderDetailsTextArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderDetailsTextArea.setForeground(new java.awt.Color(255, 255, 255));
        orderDetailsTextArea.setRows(5);
        jScrollPane1.setViewportView(orderDetailsTextArea);

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pending Orders");

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PieChartPanelLayout = new javax.swing.GroupLayout(PieChartPanel);
        PieChartPanel.setLayout(PieChartPanelLayout);
        PieChartPanelLayout.setHorizontalGroup(
            PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        PieChartPanelLayout.setVerticalGroup(
            PieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnOrderClear.setBackground(new java.awt.Color(0, 153, 51));
        btnOrderClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOrderClear.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderClear.setText("Order Completed");
        btnOrderClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(PieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNumberDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderNumberDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderClear)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderNumberDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumberDropdownActionPerformed

    }//GEN-LAST:event_orderNumberDropdownActionPerformed

    private void orderNumberDropdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderNumberDropdownMouseClicked

    }//GEN-LAST:event_orderNumberDropdownMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOrderClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderClearActionPerformed
         String selectedId = (String) orderNumberDropdown.getSelectedItem();
         PendingCompleted pc = new PendingCompleted();
         pc.deleteRecord(selectedId);
    }//GEN-LAST:event_btnOrderClearActionPerformed
     



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PieChartPanel;
    private javax.swing.JButton btnOrderClear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea orderDetailsTextArea;
    private javax.swing.JComboBox<String> orderNumberDropdown;
    // End of variables declaration//GEN-END:variables

    private void printStackTrace(Exception e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
