/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bakerypossystem.View;


import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightIJTheme;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;



/**
 *
 * @author thenu
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
  
    
    public ReportPanel() {
         try {

             FlatDarkLaf.setup();
     
        } catch (Exception e) {
        //     printStackTrace(e);
        }
        initComponents();
        Connect();
        
    }
    Connection con;
    PreparedStatement pst;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           con =  DriverManager.getConnection("jdbc:mysql://localhost/bakeryshop", "root","");
        } catch (ClassNotFoundException ex) {
           ex.printStackTrace();
        } catch (SQLException ex) {
           ex.printStackTrace();
        } 
    }
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromdate = new com.raven.datechooser.DateChooser();
        todate = new com.raven.datechooser.DateChooser();
        btnGenReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fromdte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        todte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ReportJpanel = new javax.swing.JPanel();
        btnext = new javax.swing.JButton();

        fromdate.setForeground(new java.awt.Color(0, 204, 255));
        fromdate.setDateFormat("yyyy-MM-dd ");
        fromdate.setTextRefernce(fromdte);

        todate.setForeground(new java.awt.Color(204, 0, 204));
        todate.setDateFormat("yyyy-MM-dd ");
        todate.setTextRefernce(todte);

        btnGenReport.setBackground(new java.awt.Color(0, 153, 0));
        btnGenReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenReport.setText("Generate Report");
        btnGenReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenReportActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From :");

        fromdte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromdte.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To :");

        todte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        todte.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sales Report Generate");

        javax.swing.GroupLayout ReportJpanelLayout = new javax.swing.GroupLayout(ReportJpanel);
        ReportJpanel.setLayout(ReportJpanelLayout);
        ReportJpanelLayout.setHorizontalGroup(
            ReportJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ReportJpanelLayout.setVerticalGroup(
            ReportJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        btnext.setBackground(new java.awt.Color(204, 0, 51));
        btnext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnext.setText("X");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fromdte, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todte, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(ReportJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(btnext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromdte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(todte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGenReport))
                .addGap(18, 18, 18)
                .addComponent(ReportJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnGenReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenReportActionPerformed
 

       String from = fromdte.getText();
       String to = todte.getText();

        try {
            HashMap a = new HashMap();
            a.put("fromd",from);
            a.put("tod",to);
            
            ReportJpanel.removeAll();
            ReportJpanel.repaint();;
           ReportJpanel.revalidate();
            
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\thenu\\OneDrive\\Documents\\NetBeansProjects\\BakeryPosSystem\\src\\bakerypossystem\\View\\SalesReport.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, a, con);
            
            JRViewer v = new JRViewer(jprint);
            ReportJpanel.setLayout(new BorderLayout());
           ReportJpanel.add(v);
            
            
        } catch (JRException ex) {
           
        }




        
    }//GEN-LAST:event_btnGenReportActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ReportJpanel;
    private javax.swing.JButton btnGenReport;
    private javax.swing.JButton btnext;
    private com.raven.datechooser.DateChooser fromdate;
    private javax.swing.JTextField fromdte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.raven.datechooser.DateChooser todate;
    private javax.swing.JTextField todte;
    // End of variables declaration//GEN-END:variables

    private void printStackTrace(Exception e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
